# Generated by Django 5.1.4 on 2024-12-09 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_weatherpoint_delete_weatherdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherpoint',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
