# Generated by Django 5.1.4 on 2024-12-10 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_weatherpoint_temperature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weatherpoint',
            name='climate',
        ),
        migrations.RemoveField(
            model_name='weatherpoint',
            name='humidity',
        ),
        migrations.RemoveField(
            model_name='weatherpoint',
            name='precipitation',
        ),
        migrations.RemoveField(
            model_name='weatherpoint',
            name='temperature',
        ),
        migrations.RemoveField(
            model_name='weatherpoint',
            name='wind_speed',
        ),
        migrations.CreateModel(
            name='WeatherPointDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('climate', models.CharField(blank=True, max_length=100, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('wind_speed', models.FloatField(blank=True, null=True)),
                ('precipitation', models.FloatField(blank=True, null=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('weather_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.weatherpoint')),
            ],
        ),
    ]
